matrix:
  include:
#    - language: python
#      python:
#        - 3.6
#      before_script:
#        - pip install -r requirements.txt
#        - pip install pycocotools
#      script: pytest

    - language: node_js
      node_js:
        - iojs
        - 8
      cache: npm
      before_install:
        - cd client
      install:
        - npm i
      script: npm test


