version: "3"

networks:
  cocoannotator:
    external: false

services:
  webserver:
    image: annotator_webclient_gpu
    container_name: annotator_webclient
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
      - NAME=Test Annotator
      - MASK_RCNN_FILE=/models/mask_rcnn_coco.h5
      # # Default coco classes (order matters)
      - MASK_RCNN_CLASSES=
         BG,person,bicycle,car,motorcycle,airplane,
         bus,train,truck,boat,traffic light,
         fire hydrant,stop sign,parking meter,bench,bird,
         cat,dog,horse,sheep,cow,elephant,bear,
         zebra,giraffe,backpack,umbrella,handbag,tie,
         suitcase,frisbee,skis,snowboard,sports ball,
         kite,baseball bat,baseball glove,skateboard,
         surfboard,tennis racket,bottle,wine glass,cup,
         fork,knife,spoon,bowl,banana',apple,
         sandwich,orange,broccoli,carrot,hot dog,pizza,
         donut,cake,chair,couch,potted plant,bed,
         dining table,toilet,tv,laptop,mouse,remote,
         keyboard,cell phone,microwave,oven,toaster,
         sink,refrigerator,book,clock,vase,scissors,
         teddy bear,hair drier,toothbrush
    volumes:
      - "./datasets:/datasets"
      - "./models:/models"
    depends_on:
      - database
      - workers
    networks:
      - cocoannotator
  workers:
    container_name: annotator_workers
    image: annotator_workers_gpu
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    ports:
      - 5555:5555
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
    networks:
      - cocoannotator
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: "no"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./db:/data/db"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
