version: "3"
volumes:
  mongodb_data:
    external: false
networks:
  cocoannotator:
    external: false

services:
  frontend:
    container_name: annotator_client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./client:/workspace/client"
    networks:
      - cocoannotator
    depends_on:
      - flask
  flask:
    container_name: annotator_flask
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./datasets:/datasets"
      - "./:/workspace/"
      - "./.git:/workspace/.git"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=app
      - FLASK_ENV=development
    networks:
      - cocoannotator
    depends_on:
      - database
    tty: true
  database:
    image: mongo:4
    container_name: annotator_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
